### ISSUE TITLE
Sotsiaalmeedia ja otsingumootorite jaoks lisada meta tag'id

### ISSUE THREAD

**Issue by viljark** [Iglu-OU/IgluDA#10]
keywords, og:image, og:title, og:url, og:site_name, og:description.

**Comment by viljark** [comment]
Praegu võrdlemisi inetu tulemus:
http://img.iglu.ee/public/c1d2c45b-cf58-4ed2-8b92-1973c4891625.png

**Comment by ivarkallejarv** [comment]
Fixed, resource for checking implementation - https://opengraphcheck.com/
